PAGES = {
    "index": "https://ootw25.ca/",
    "space-blog": "https://ootw25.ca/space-blog/",
    "ootw25-news": "https://ootw25.ca/ootw25-news/",
    "partners": "https://ootw25.ca/partners/",
    "canada-in-space-storymaps": "https://ootw25.ca/canada-in-space-storymaps/",
    "microhistories": "https://ootw25.ca/microhistories/",
    "educators": "https://ootw25.ca/educators/",
    "students-and-families": "https://ootw25.ca/students-and-families/",
    "artemis-ii-mission": "https://ootw25.ca/artemis-ii-mission/",
    "canadian-space-history": "https://ootw25.ca/canadian-space-history/",
    "contact-us": "https://ootw25.ca/contact-us/",
    "who-are-we": "https://ootw25.ca/who-are-we/",
    "privacy-policy": "https://ootw25.ca/privacy-policy/",
    "ootw25-neil-orford": "https://ootw25.ca/ootw25-neil-orford/",
    "commemorating-col-hadfields-spacewalk": "https://ootw25.ca/commemorating-col-hadfields-spacewalk/",
    "out-of-this-world-25-ootw25-official-press-release": "https://ootw25.ca/out-of-this-world-25-ootw25-official-press-release/",
    "chris-hadfield-from-dreaming-of-space-to-leading-the-iss": "https://ootw25.ca/chris-hadfield-from-dreaming-of-space-to-leading-the-iss/",
    "canadian-history-ehx-biography-chris-hadfield": "https://ootw25.ca/canadian-history-ehx-biography-chris-hadfield/",
}
